/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication5;

import java.awt.Cursor;
import javax.swing.JOptionPane;

/**
 *
 * @author frain
 */
public class Inicio extends javax.swing.JFrame {
    
    public String nomes;
    
    Jogo abrir = new Jogo();
    
    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rank = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        jogar1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        rank.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        rank.setForeground(new java.awt.Color(0, 0, 0));
        rank.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rank.setText("Ver Ranking");
        rank.setToolTipText("");
        rank.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rank.setVerifyInputWhenFocusTarget(false);
        rank.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rankMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rankMouseEntered(evt);
            }
        });
        getContentPane().add(rank);
        rank.setBounds(390, 480, 240, 60);

        nome.setBackground(new java.awt.Color(255, 255, 255));
        nome.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        nome.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nome.setBorder(null);
        getContentPane().add(nome);
        nome.setBounds(300, 280, 410, 100);

        jogar1.setFont(new java.awt.Font("Segoe UI", 1, 70)); // NOI18N
        jogar1.setForeground(new java.awt.Color(0, 0, 0));
        jogar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jogar1.setText("JOGAR");
        jogar1.setToolTipText("");
        jogar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jogar1.setVerifyInputWhenFocusTarget(false);
        jogar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jogar1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jogar1MouseEntered(evt);
            }
        });
        getContentPane().add(jogar1);
        jogar1.setBounds(240, 550, 540, 150);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/inicio_1.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-3, -4, 1030, 780);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rankMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rankMouseClicked
        Ranking abrirRank = new Ranking();
        abrirRank.setVisible(true);
        abrirRank.setSize(1034, 798);
        abrirRank.setLocationRelativeTo(null);
        abrirRank.setResizable(false);
        dispose();
    }//GEN-LAST:event_rankMouseClicked

    private void rankMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rankMouseEntered
        // TODO add your handling code here:
        rank.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_rankMouseEntered

    private void jogar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jogar1MouseClicked
        nomes = nome.getText();
        if(nomes.isBlank()||nomes.isEmpty()||nomes.length()>29) {
            JOptionPane.showMessageDialog(null, "Há um erro de digitação no campo de nome!");
        }else{
            Jogo abrirJogo = new Jogo();
            abrirJogo.nomes = nomes;
            abrirJogo.setVisible(true);
            abrirJogo.setSize(1034, 798);
            abrirJogo.setLocationRelativeTo(null);
            abrirJogo.setResizable(false);
            dispose();
        }
        
    }//GEN-LAST:event_jogar1MouseClicked

    private void jogar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jogar1MouseEntered
        jogar1.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jogar1MouseEntered

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Inicio cleber = new Inicio();
                cleber.setVisible(true);
                cleber.setSize(1034, 798);
                cleber.setLocationRelativeTo(null);
                cleber.setResizable(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jogar1;
    private javax.swing.JTextField nome;
    private javax.swing.JLabel rank;
    // End of variables declaration//GEN-END:variables
}
