/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication5;

import java.awt.Cursor;

/**
 *
 * @author frain
 */
public class Perdeu extends javax.swing.JFrame {

    public double pontuacao2;
    
    public Perdeu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jogar = new javax.swing.JLabel();
        perdou = new javax.swing.JLabel();
        pontPerde1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jogar.setFont(new java.awt.Font("Segoe UI", 1, 50)); // NOI18N
        jogar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jogar.setText("Início");
        jogar.setToolTipText("");
        jogar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jogar.setVerifyInputWhenFocusTarget(false);
        jogar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jogarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jogarMouseEntered(evt);
            }
        });
        getContentPane().add(jogar);
        jogar.setBounds(270, 540, 480, 160);

        perdou.setFont(new java.awt.Font("Segoe UI", 1, 80)); // NOI18N
        perdou.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        perdou.setText("aaaa");
        perdou.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(perdou);
        perdou.setBounds(200, 70, 620, 110);

        pontPerde1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        pontPerde1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(pontPerde1);
        pontPerde1.setBounds(287, 276, 440, 110);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Perdeu !.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-3, -4, 1030, 780);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jogarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jogarMouseClicked
        Inicio abrirInicio = new Inicio();
        abrirInicio.setVisible(true);
        abrirInicio.setSize(1034, 798);
        abrirInicio.setLocationRelativeTo(null);
        abrirInicio.setResizable(false);
        dispose();
    }//GEN-LAST:event_jogarMouseClicked

    private void jogarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jogarMouseEntered
        // TODO add your handling code here:
        jogar.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jogarMouseEntered

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        pontPerde1.setText(String.valueOf(pontuacao2));
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Perdeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Perdeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Perdeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Perdeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Perdeu cleber = new Perdeu();
                cleber.setVisible(true);
                cleber.setSize(1034, 798);
                cleber.setLocationRelativeTo(null);
                cleber.setResizable(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jogar;
    public javax.swing.JLabel perdou;
    private javax.swing.JLabel pontPerde1;
    // End of variables declaration//GEN-END:variables
}
