/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication5;

import java.awt.Cursor;

/**
 *
 * @author frain
 */
public class Ranking extends javax.swing.JFrame {

    JConnectorDB dados = new JConnectorDB();
    
    public Ranking() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        voltar = new javax.swing.JLabel();
        pontos = new javax.swing.JLabel();
        nomes = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        voltar.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        voltar.setForeground(new java.awt.Color(0, 0, 0));
        voltar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        voltar.setText("Voltar");
        voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                voltarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                voltarMouseEntered(evt);
            }
        });
        getContentPane().add(voltar);
        voltar.setBounds(770, 50, 200, 60);

        pontos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        pontos.setForeground(new java.awt.Color(0, 0, 0));
        pontos.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        pontos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pontos.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        getContentPane().add(pontos);
        pontos.setBounds(620, 210, 330, 550);

        nomes.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        nomes.setForeground(new java.awt.Color(0, 0, 0));
        nomes.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        nomes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        nomes.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        getContentPane().add(nomes);
        nomes.setBounds(100, 210, 460, 550);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Pontuação");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(600, 140, 350, 50);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Nome");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 140, 460, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/rank.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1030, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        String[][] dados2 = new String[15][2];
        dados2 = dados.ConsultaRank("SELECT * FROM `tb_ranking` ORDER BY `pontos` DESC LIMIT 15");
        
        nomes.setText("<html>");
        pontos.setText("<html>");
        for(int i =0; i<=14; i++) {
            int placar = i+1;
            if(dados2[i][0] !=null) {
                if(i==0) {
                    nomes.setText(nomes.getText()+"0"+placar+" - "+dados2[i][0]);
                    pontos.setText(pontos.getText()+dados2[i][1]);
                } else if(i<9 && i>0) {
                    nomes.setText(nomes.getText()+"<br/>0"+placar+" - "+dados2[i][0]);
                    pontos.setText(pontos.getText()+"<br>"+dados2[i][1]);
                } else {
                    nomes.setText(nomes.getText()+"<br/>"+placar+" - "+dados2[i][0]);
                    pontos.setText(pontos.getText()+"<br>"+dados2[i][1]);
                }
            }
        }
        pontos.setText(pontos.getText()+"</html>");
        nomes.setText(nomes.getText()+"</html>");
        
    }//GEN-LAST:event_formWindowOpened

    private void voltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarMouseClicked
        Inicio vInicio = new Inicio();
        vInicio.setVisible(true);
        vInicio.setSize(1034, 798);
        vInicio.setLocationRelativeTo(null);
        vInicio.setResizable(false);
        dispose();
    }//GEN-LAST:event_voltarMouseClicked

    private void voltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarMouseEntered
        voltar.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_voltarMouseEntered

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ranking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ranking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ranking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ranking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ranking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel nomes;
    private javax.swing.JLabel pontos;
    private javax.swing.JLabel voltar;
    // End of variables declaration//GEN-END:variables
}
